# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push

env:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository
  MAVEN_CLI_OPTS: --strict-checksums --threads 4C --batch-mode

jobs:
  build:
    runs-on: ubuntu-latest        
    steps:
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '17'
          maven-version: '3.8.5'
      - name: Verify Maven SetUp
        run: mvn verify
      - name: Build with Maven
        run: mvn $MAVEN_CLI_OPTS $MAVEN_OPTS compile
